In [1]:
!pip install langchain
!pip install -U langchain-community

Requirement already satisfied: langchain in /usr/local/lib/python3.11/dist-packages (0.3.24)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.55 in /usr/local/lib/python3.11/dist-packages (from langchain) (0.3.56)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.8 in /usr/local/lib/python3.11/dist-packages (from langchain) (0.3.8)
Requirement already satisfied: langsmith<0.4,>=0.1.17 in /usr/local/lib/python3.11/dist-packages (from langchain) (0.3.38)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.11/dist-packages (from langchain) (2.11.3)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from langchain) (2.0.40)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.11/dist-packages (from langchain) (2.32.3)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.11/dist-packages (from langchain) (6.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.55->langchain) (9.1.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.55->langchain) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.55->langchain) (24.2)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.55->langchain) (4.13.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.17->langchain) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.17->langchain) (3.10.17)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.17->langchain) (0.23.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (2025.4.26)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy<3,>=1.4->langchain) (3.2.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (4.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.55->langchain) (3.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (1.3.1)
Collecting langchain-community
  Downloading langchain_community-0.3.23-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.56 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (0.3.56)
Requirement already satisfied: langchain<1.0.0,>=0.3.24 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (0.3.24)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (2.0.40)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (2.32.3)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (6.0.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (3.11.15)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (9.1.2)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain-community)
  Downloading pydantic_settings-2.9.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: langsmith<0.4,>=0.1.125 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (0.3.38)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.20.0)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.8 in /usr/local/lib/python3.11/dist-packages (from langchain<1.0.0,>=0.3.24->langchain-community) (0.3.8)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.11/dist-packages (from langchain<1.0.0,>=0.3.24->langchain-community) (2.11.3)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.56->langchain-community) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.56->langchain-community) (24.2)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.56->langchain-community) (4.13.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (3.10.17)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (0.23.0)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.4.0->langchain-community)
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic-settings<3.0.0,>=2.4.0->langchain-community) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain-community) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain-community) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain-community) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain-community) (2025.4.26)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy<3,>=1.4->langchain-community) (3.2.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-community) (4.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.56->langchain-community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<1.0.0,>=0.3.24->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<1.0.0,>=0.3.24->langchain-community) (2.33.1)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-community) (1.3.1)
Downloading langchain_community-0.3.23-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 25.0 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.0-py3-none-any.whl (7.8 kB)
Downloading pydantic_settings-2.9.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 1.3 MB/s eta 0:00:00
Downloading marshmallow-3.26.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.3 MB/s eta 0:00:00
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: python-dotenv, mypy-extensions, marshmallow, httpx-sse, typing-inspect, pydantic-settings, dataclasses-json, langchain-community
Successfully installed dataclasses-json-0.6.7 httpx-sse-0.4.0 langchain-community-0.3.23 marshmallow-3.26.1 mypy-extensions-1.1.0 pydantic-settings-2.9.1 python-dotenv-1.1.0 typing-inspect-0.9.0

In [ ]:
from langchain.document_loaders import TextLoader

In [5]:
loader = TextLoader("nvda_news_1.txt")
data = loader.load()

In [6]:
data[0].metadata

{'source': 'nvda_news_1.txt'}

In [7]:
from langchain.document_loaders.csv_loader import CSVLoader


loader = CSVLoader("movies.csv", source_column="title")
data = loader.load()

In [8]:
len(data)

9

In [9]:
data[0].page_content

'movie_id: 101\ntitle: K.G.F: Chapter 2\nindustry: Bollywood\nrelease_year: 2022\nimdb_rating: 8.4\nstudio: Hombale Films\nlanguage_id: 3\nbudget: 1\nrevenue: 12.5\nunit: Billions\ncurrency: INR'

In [10]:
data[1].metadata

{'source': 'Doctor Strange in the Multiverse of Madness', 'row': 1}

In [11]:
#installing necessary library libmagic is used for file type detection
!pip3 install unstructured libmagic python-magic

Collecting unstructured
  Downloading unstructured-0.17.2-py3-none-any.whl.metadata (24 kB)
Collecting libmagic
  Downloading libmagic-1.0.tar.gz (3.7 kB)
  Preparing metadata (setup.py) ... done
Collecting python-magic
  Downloading python_magic-0.4.27-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: chardet in /usr/local/lib/python3.11/dist-packages (from unstructured) (5.2.0)
Collecting filetype (from unstructured)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from unstructured) (5.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from unstructured) (3.9.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from unstructured) (2.32.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from unstructured) (4.13.4)
Collecting emoji (from unstructured)
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.11/dist-packages (from unstructured) (0.6.7)
Collecting python-iso639 (from unstructured)
  Downloading python_iso639-2025.2.18-py3-none-any.whl.metadata (14 kB)
Collecting langdetect (from unstructured)
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 17.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from unstructured) (2.0.2)
Collecting rapidfuzz (from unstructured)
  Downloading rapidfuzz-3.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting backoff (from unstructured)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from unstructured) (4.13.2)
Collecting unstructured-client (from unstructured)
  Downloading unstructured_client-0.34.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from unstructured) (1.17.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from unstructured) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from unstructured) (5.9.5)
Collecting python-oxmsg (from unstructured)
  Downloading python_oxmsg-0.0.2-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: html5lib in /usr/local/lib/python3.11/dist-packages (from unstructured) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->unstructured) (2.7)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json->unstructured) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json->unstructured) (0.9.0)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.11/dist-packages (from html5lib->unstructured) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from html5lib->unstructured) (0.5.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->unstructured) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->unstructured) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk->unstructured) (2024.11.6)
Collecting olefile (from python-oxmsg->unstructured)
  Downloading olefile-0.47-py2.py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->unstructured) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->unstructured) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->unstructured) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->unstructured) (2025.4.26)
Collecting aiofiles>=24.1.0 (from unstructured-client->unstructured)
  Downloading aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: cryptography>=3.1 in /usr/local/lib/python3.11/dist-packages (from unstructured-client->unstructured) (43.0.3)
Collecting eval-type-backport>=0.2.0 (from unstructured-client->unstructured)
  Downloading eval_type_backport-0.2.2-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.11/dist-packages (from unstructured-client->unstructured) (0.28.1)
Requirement already satisfied: nest-asyncio>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from unstructured-client->unstructured) (1.6.0)
Requirement already satisfied: pydantic>=2.11.2 in /usr/local/lib/python3.11/dist-packages (from unstructured-client->unstructured) (2.11.3)
Collecting pypdf>=4.0 (from unstructured-client->unstructured)
  Downloading pypdf-5.4.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from unstructured-client->unstructured) (1.0.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from unstructured-client->unstructured) (0.4.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=3.1->unstructured-client->unstructured) (1.17.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->unstructured-client->unstructured) (4.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->unstructured-client->unstructured) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.27.0->unstructured-client->unstructured) (0.16.0)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.11/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->unstructured) (24.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.11.2->unstructured-client->unstructured) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.11.2->unstructured-client->unstructured) (2.33.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->unstructured) (1.1.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=3.1->unstructured-client->unstructured) (2.22)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.27.0->unstructured-client->unstructured) (1.3.1)
Downloading unstructured-0.17.2-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 75.4 MB/s eta 0:00:00
Downloading python_magic-0.4.27-py2.py3-none-any.whl (13 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 46.9 MB/s eta 0:00:00
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading python_iso639-2025.2.18-py3-none-any.whl (167 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.6/167.6 kB 17.4 MB/s eta 0:00:00
Downloading python_oxmsg-0.0.2-py3-none-any.whl (31 kB)
Downloading rapidfuzz-3.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 98.0 MB/s eta 0:00:00
Downloading unstructured_client-0.34.0-py3-none-any.whl (189 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.4/189.4 kB 19.1 MB/s eta 0:00:00
Downloading aiofiles-24.1.0-py3-none-any.whl (15 kB)
Downloading eval_type_backport-0.2.2-py3-none-any.whl (5.8 kB)
Downloading pypdf-5.4.0-py3-none-any.whl (302 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.3/302.3 kB 26.5 MB/s eta 0:00:00
Downloading olefile-0.47-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 kB 11.9 MB/s eta 0:00:00
Building wheels for collected packages: libmagic, langdetect
  Building wheel for libmagic (setup.py) ... done
  Created wheel for libmagic: filename=libmagic-1.0-py3-none-any.whl size=4269 sha256=ca29085e053d36597df0dded7ba2b912f7636918422f0ec767cff5323f777cd0
  Stored in directory: /root/.cache/pip/wheels/3e/35/13/53c696ff5f3523479505ec5ed4156198671fb598fe678178bf
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=b206291a33d2c7224eb040533e18750b4d95f3b6225b0fbeddd38d3152c39f9e
  Stored in directory: /root/.cache/pip/wheels/0a/f2/b2/e5ca405801e05eb7c8ed5b3b4bcf1fcabcd6272c167640072e
Successfully built libmagic langdetect
Installing collected packages: libmagic, filetype, rapidfuzz, python-magic, python-iso639, pypdf, olefile, langdetect, eval-type-backport, emoji, backoff, aiofiles, python-oxmsg, unstructured-client, unstructured
Successfully installed aiofiles-24.1.0 backoff-2.2.1 emoji-2.14.1 eval-type-backport-0.2.2 filetype-1.2.0 langdetect-1.0.9 libmagic-1.0 olefile-0.47 pypdf-5.4.0 python-iso639-2025.2.18 python-magic-0.4.27 python-oxmsg-0.0.2 rapidfuzz-3.13.0 unstructured-0.17.2 unstructured-client-0.34.0

In [12]:
from langchain.document_loaders import UnstructuredURLLoader

In [13]:
loader = UnstructuredURLLoader(urls=[
    "https://www.moneycontrol.com/news/business/markets/wall-street-rises-as-tesla-soars-on-ai-optimism-11351111.html",
    "https://www.moneycontrol.com/news/business/tata-motors-launches-punch-icng-price-starts-at-rs-7-1-lakh-11098751.html"
])

In [14]:
data = loader.load()
len(data)

2

In [15]:
data[0]

Document(metadata={'source': 'https://www.moneycontrol.com/news/business/markets/wall-street-rises-as-tesla-soars-on-ai-optimism-11351111.html'}, page_content='English\n\nHindi\n\nGujarati\n\nSpecials\n\nHello, Login\n\nHello, Login\n\nLog-inor Sign-Up\n\nMy Account\n\nMy Profile\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nMy Profile\n\nMy PRO\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nLogout\n\nLoans up to ₹50 LAKHS\n\nFixed Deposits\n\nCredit CardsLifetime Free\n\nCredit Score\n\nChat with Us\n\nDownload App\n\nFollow us on:\n\nNetwork 18\n\nGo Ad-Free\n\nMy Alerts\n\n>->MC_ENG_DESKTOP/MC_ENG_NEWS/MC_ENG_MARKETS_AS/MC_ENG_ROS_NWS_MKTS_AS_ATF_728\n\nMoneycontrol\n\nGo PRO NowPRO\n\nMoneycontrol PRO\n\nAdvertisement\n\nRemove Ad\n\nBusiness\n\nMarkets\n\nStocks\n\nEconomy\n\nCompanies\n\nTrends\n\nIPO\n\nOpinion\n\nEV Special\n\nOffer Subscription Products\n\nprofile\n\nAmbareesh Baliga\n\nprofile\n\nCK Narayan\n\nprofile\n\nT Gnanasekar\n\nprofile\n\nPower Your Trade\n\nprofile\n\nCurrencies with Mecklai Financial\n\nprofile\n\nStock Reports\n\nHomeNewsBusinessMarketsWall Street rises as Tesla soars on AI optimism\n\nTrending Topics\n\nSensex TodayIndusInd Bank Share PriceUltraTech Cement Share PriceRIL Share PriceSushil KediaSML Isuzu Share Price\n\nWall Street rises as Tesla soars on AI optimism\n\nTesla (TSLA.O) rallied 10% after Morgan Stanley upgraded the electric car maker to "overweight" from "equal-weight," saying its Dojo supercomputer could boost the company\'s market value by nearly $600 billion.\n\nReuters\n\nSeptember 12, 2023 / 06:56 IST\n\nWall Street rises as Tesla soars on AI optimism\n\nWall Street rises as Tesla soars on AI optimism\n\nThe Nasdaq closed sharply higher on Monday as Tesla surged on optimism around artificial intelligence and investors awaited inflation data due later this week.\n\nTesla (TSLA.O) rallied 10% after Morgan Stanley upgraded the electric car maker to "overweight" from "equal-weight," saying its Dojo supercomputer could boost the company\'s market value by nearly $600 billion.\n\nStory continues below Advertisement\n\nRemove Ad\n\nOther megacaps also rose, with Amazon (AMZN.O) climbing 3.5% and Microsoft (MSFT.O) adding 1.1%.\n\nMeta Platforms (META.O) jumped 3.25% after a report on Sunday said the social media platform was working on a new, more powerful AI system.\n\nWalt Disney (DIS.N) added 1.2% and Charter Communications (CHTR.O) rose 3.2% after they reached a deal for Disney\'s programming, including ESPN, to return to the Spectrum cable service just hours ahead of the start of NFL "Monday Night Football."\n\nRelated stories\n\nWall Street ends with weekly gains as trade negotiations, earnings in focus\n\nWall Street ends with weekly gains as trade negotiations, earnings in focus\n\nWall Street ends whipsaw week sharply higher as Fed comments soothe market\n\nWall Street ends whipsaw week sharply higher as Fed comments soothe market\n\nTrump tariff tailspin worsens, Nasdaq confirms in bear market\n\nTrump tariff tailspin worsens, Nasdaq confirms in bear market\n\nInvestors are looking to August consumer price index data due on Wednesday for clues about how close the Federal Reserve may be to ending its campaign of interest rate hikes. That will be followed by producer price data on Thursday.\n\nA New York Fed survey showed Americans\' overall views on inflation were little changed in August, as they predicted rising costs for homes and food, while expecting bleaker personal financial health.\n\n"What we\'re seeing is a lot of positive sentiment that is really tied to bullishness around the likely CPI and PPI numbers being more in line with moderation," said Greg Bassuk, chief executive officer of AXS Investments in New York.\n\nStory continues below Advertisement\n\nRemove Ad\n\n"As long as the inflation numbers for August come in within the band of expectations, we\'re going to see the Fed move away from additional rate hikes."\n\nWall Street logged weekly losses on Friday after a recent uptick in oil prices and stronger-than-expected economic data fueled concerns of sticky inflation and interest rates staying higher for longer.\n\nTraders see a 93% chance that the central bank will hold its interest rates at current levels at its September meeting, while chances of a pause in November stand at 57%, according to the CME FedWatch Tool. Fed officials have entered a blackout period, during which they usually do not make public comments, until the policy decision outcome on Sept. 20.\n\nThe S&P 500 climbed 0.67% to end at 4,487.46 points.\n\nThe Nasdaq gained 1.14% at 13,917.89 points, while Dow Jones Industrial Average rose 0.25% to 34,663.72 points.\n\nVolume on U.S. exchanges was relatively light, with 9.3 billion shares traded, compared to an average of 10.0 billion shares over the previous 20 sessions.\n\nOf the 11 S&P 500 sector indexes, nine rose, led by consumer discretionary (.SPLRCD), up 2.77%, followed by a 1.17% gain in communication services (.SPLRCL).\n\nQualcomm (QCOM.O) advanced 3.9% after the chipmaker signed a new deal with Apple (AAPL.O) to supply 5G chips to the iPhone maker until at least 2026.\n\nHostess Brands (TWNK.O) surged 19.1% after J. M. Smucker (SJM.N) said it would buy the Twinkies-maker in a $5.6 billion deal.\n\nAdvancing issues outnumbered falling ones within the S&P 500 (.AD.SPX) by a 1.5-to-one ratio.\n\nThe S&P 500 posted 14 new highs and 11 new lows; the Nasdaq recorded 36 new highs and 199 new lows.\n\nReuters\n\nfirst published: Sep 12, 2023 06:24 am\n\nDiscover the latest Business News, Budget 2025 News, Sensex, and Nifty updates. Obtain Personal Finance insights, tax queries, and expert opinions on Moneycontrol or download the Moneycontrol App to stay updated!\n\nAdvertisement\n\nRemove Ad\n\nTrending news\n\nStudy finds common trait behind Bill Gates, Mark Zuckerberg, Steve Jobs’ success. It’s not what you think\n\n‘Dream job’ in UAE: House manager role paying Rs 7 lakh a month goes viral\n\n‘Don’t guard your weekends’: Delhi CEO’s take on work-life balance sparks viral debate\n\nIndian-origin startup founder criticised for calling out ex-employee over viral firing post: \'Sob story\'\n\nGroom carries ailing bride for \'saat phere\' as MP hospital turns wedding venue. Watch\n\nAdvisory Alert:\n\nmoneycontrol\n\nFollow Us On:\n\nFacebook\n\ntwitter\n\ninstagram\n\nlinkedin\n\ntelegram\n\nyoutube\n\nStocks: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Others\n\nTrending Topics\n\nTrading Plan Jammu Kashmir News Live Australia Election Results Singapore Election Results PM Modi on Shashi Tharoor Odisha 10th Result 2025 Ganga Expressway Indian Rupee Hyderabad Water Crisis IPL Points Table 2025\n\nNews\n\nBusiness Markets Stocks India News City News Economy Mutual Funds Personal Finance IPO News Startups\n\nMarkets\n\nHome Currencies Commodities Pre-Market IPO Global Market Bonds\n\nPersonal Finance\n\nHome Loans up to 50 Lakhs Credit Cards Lifetime Free Finance TrackerNew Fixed Deposits Fixed Deposit Comparison Fixed Income\n\nMutual Funds\n\nHome MC 30 Top Ranked Funds ETFs Mutual Fund Screener\n\nTools\n\nIncome Tax Calculator EMI Calculator Retirement Planning Gratuity Calculator\n\nCommunity\n\nStock Markets\n\nNetwork 18 Sites\n\nNews18 Firstpost CNBC TV18 News18 Hindi Cricketnext Overdrive Topper Learning\n\nQuick Links\n\nAbout Us Contact Us Advisory Alert Advertise with Us SupportDisclaimer Privacy Policy Cookie Policy Terms & Conditions Financial Terms (Glossary) Sitemap Investors\n\nDownload MC Apps:\n\n\n\n\n\n\n\nCopyright © Network18 Media & Investments Limited. All rights reserved. Reproduction of news articles, photos, videos or any other content in whole or in part in any form or medium without express written permission of moneycontrol.com is prohibited.\n\nYou got 30 Day’s Trial of\n\nMoneycontrol Pro\n\nMoneycontrol Pro\n\nGrab it Now\n\nAd-Free Experience\n\nTop Articles from Financial Times\n\nTop Articles from Financial Times\n\nActionable Insights\n\nMC Research\n\nEconomic Calendar\n\n& Many More\n\n& Many More\n\nYou are already a Moneycontrol Pro user.\n\nBe Prepared with PRO\n\nBe Prepared with PRO\n\nFaizan Javed')

In [16]:
data[0].metadata

{'source': 'https://www.moneycontrol.com/news/business/markets/wall-street-rises-as-tesla-soars-on-ai-optimism-11351111.html'}

Text splittiing

In [17]:
# Taking some random text from wikipedia

text = """Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan.
It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine.
Set in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.

Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007 and was originally set to be directed by Steven Spielberg.
Kip Thorne, a Caltech theoretical physicist and 2017 Nobel laureate in Physics,[4] was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar.
Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm. Principal photography began in late 2013 and took place in Alberta, Iceland, and Los Angeles.
Interstellar uses extensive practical and miniature effects, and the company Double Negative created additional digital effects.

Interstellar premiered in Los Angeles on October 26, 2014. In the United States, it was first released on film stock, expanding to venues using digital projectors. The film received generally positive reviews from critics and grossed over $677 million worldwide ($715 million after subsequent re-releases), making it the tenth-highest-grossing film of 2014.
It has been praised by astronomers for its scientific accuracy and portrayal of theoretical astrophysics.[5][6][7] Interstellar was nominated for five awards at the 87th Academy Awards, winning Best Visual Effects, and received numerous other accolades."""

In [18]:
from langchain.text_splitter import CharacterTextSplitter

splitter = CharacterTextSplitter(
    separator='\n',
    chunk_size=200,
    chunk_overlap=0
)

chunks = splitter.split_text(text)
len(chunks)

WARNING:langchain_text_splitters.base:Created a chunk of size 210, which is longer than the specified 200
WARNING:langchain_text_splitters.base:Created a chunk of size 207, which is longer than the specified 200
WARNING:langchain_text_splitters.base:Created a chunk of size 357, which is longer than the specified 200

9

In [19]:
chunks

['Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan.',
 'It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine.',
 'Set in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.',
 'Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007 and was originally set to be directed by Steven Spielberg.',
 'Kip Thorne, a Caltech theoretical physicist and 2017 Nobel laureate in Physics,[4] was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar.',
 'Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm. Principal photography began in late 2013 and took place in Alberta, Iceland, and Los Angeles.',
 'Interstellar uses extensive practical and miniature effects, and the company Double Negative created additional digital effects.',
 'Interstellar premiered in Los Angeles on October 26, 2014. In the United States, it was first released on film stock, expanding to venues using digital projectors. The film received generally positive reviews from critics and grossed over $677 million worldwide ($715 million after subsequent re-releases), making it the tenth-highest-grossing film of 2014.',
 'It has been praised by astronomers for its scientific accuracy and portrayal of theoretical astrophysics.[5][6][7] Interstellar was nominated for five awards at the 87th Academy Awards, winning Best Visual Effects, and received numerous other accolades.']

In [20]:
for chunk in chunks:
  print(len (chunk))

105
120
210
181
197
207
128
357
253

In [21]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

r_splitter = RecursiveCharacterTextSplitter(
     separators=["n\n","\n"," "],
    chunk_size=200,
    chunk_overlap=0
)
chunks = r_splitter.split_text(text)
len(chunks)

13

In [22]:
for chunk in chunks:
  print(len (chunk))

105
120
199
10
181
197
198
8
128
191
165
198
54

In [23]:
chunks = text.split("\n\n")
for chunk in chunks:
  print(len(chunk))

437
716
611

In [24]:
chunks[0]

'Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan.\nIt stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine.\nSet in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.'

In [25]:
first_split = chunks[0]
first_split

'Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan.\nIt stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine.\nSet in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.'

In [26]:
second_split = first_split.split("\n")

In [27]:
len(second_split[2])

210

Faiss

In [28]:
#install packages
!pip install faiss-cpu
!pip install sentence-transformers

Collecting faiss-cpu
  Downloading faiss_cpu-1.11.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.11/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from faiss-cpu) (24.2)
Downloading faiss_cpu-1.11.0-cp311-cp311-manylinux_2_28_x86_64.whl (31.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.3/31.3 MB 63.0 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.11.0
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (3.4.1)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.51.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.15.2)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (0.30.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.4.26)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.1 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 108.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 86.0 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 56.1 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.5 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.2 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.9 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 81.9 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [31]:
import pandas as pd


pd.set_option('display.max_colwidth', 100)

In [32]:
df=pd.read_csv('sample_text.csv')

In [33]:
df.shape

(8, 2)

In [34]:
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel

In [35]:
#Step 1 : Create source embeddings for the text column
from sentence_transformers import  SentenceTransformer

SentenceTransformer("all-mpnet-base-v2")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

SentenceTransformer(
  (0): Transformer({'max_seq_length': 384, 'do_lower_case': False}) with Transformer model: MPNetModel
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [36]:
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

In [37]:
vectors.shape

(8, 768)

In [38]:
dim = vectors.shape[1]
dim

768

In [39]:
#Step 2 : Build a FAISS Index for vectors
import faiss

index = faiss.IndexFlatL2(dim)

In [40]:
#Step 3 : Normalize the source vectors (as we are using L2 distance to measure similarity) and add to the index
index.add(vectors)

In [41]:
index

In [42]:
#Step 4 : Encode search text using same encorder and normalize the output vector
search_query = "I want to buy a polo t-shirt"
# search_query = "looking for places to visit during the holidays"
# search_query = "An apple a day keeps the doctor away"
vec = encoder.encode(search_query)
vec.shape

(768,)

In [43]:
vec

array([ 1.03882691e-02,  2.78686285e-02, -1.18618710e-02,  1.81327257e-02,
        1.21984119e-03, -1.42995641e-02,  1.96229368e-02,  2.07198318e-02,
       -2.23660935e-02,  4.75626774e-02,  1.77976061e-02, -8.00333917e-03,
        2.53419522e-02,  5.26148640e-02,  8.44942406e-03, -1.63944215e-02,
        1.02661494e-02, -2.74856109e-02,  8.37067291e-02, -1.52885355e-02,
        1.67682748e-02, -3.97142116e-03, -2.74348632e-02,  5.02091758e-02,
       -8.36521294e-03, -4.74075824e-02,  2.36915816e-02, -1.01186438e-02,
       -2.82840263e-02,  7.94265140e-03,  4.21436168e-02, -4.19375999e-03,
       -1.91232357e-02, -3.12785394e-02,  1.24685050e-06, -1.04428437e-02,
       -2.19971444e-02, -8.66928026e-02, -1.88494497e-03, -2.54772231e-02,
       -9.72972624e-03,  7.93310255e-02, -3.55963632e-02, -3.05383728e-04,
       -1.12392241e-02, -3.88932489e-02,  5.49313761e-02,  1.35207981e-01,
       -8.19147453e-02,  1.18785072e-02, -9.01845656e-03,  1.92544367e-02,
       -2.82723568e-02, -3.29266936e-02, -2.20106654e-02, -4.29835916e-02,
        3.70104685e-02, -4.80649248e-02,  9.49257892e-03,  3.51585783e-02,
        4.88772467e-02, -3.28933634e-02, -1.24120517e-02, -1.64292939e-02,
        3.93721089e-02,  2.69109719e-02,  6.15458935e-02, -4.14122455e-03,
        1.75675526e-02,  1.53993415e-02,  9.60058253e-03, -5.69588272e-04,
       -4.83582541e-02,  4.25832123e-02,  1.10986000e-02, -4.66182418e-02,
       -2.10591801e-03, -5.81461154e-02,  1.40413018e-02,  1.00883860e-02,
       -2.44589858e-02,  1.42714167e-02, -2.10582279e-02,  7.38854259e-02,
       -2.23948881e-02,  1.38753317e-02, -1.33594673e-03,  9.21318494e-03,
       -2.84222756e-02, -4.04207641e-03, -1.71393286e-02, -8.46521184e-03,
       -2.83984020e-02, -3.69299464e-02, -9.47201177e-02, -3.26580219e-02,
        2.60049943e-02,  1.31179057e-02,  1.51670882e-02, -2.12378916e-03,
        1.48178022e-02,  1.37817143e-02,  1.25304116e-02, -5.01475437e-03,
        3.56063135e-02,  5.93453869e-02, -5.03397435e-02, -9.55990888e-03,
       -7.23668933e-02,  9.45845246e-03,  1.54202739e-02, -7.03747384e-03,
       -3.10014673e-02, -8.86358973e-03, -2.98000704e-02, -8.84007737e-02,
       -2.25058924e-02, -3.25824358e-02,  4.78070490e-02,  2.14029476e-03,
        1.37757114e-03, -1.25066238e-02, -1.15712602e-02,  2.34021824e-02,
        3.43833375e-03,  2.69363020e-02, -6.23307340e-02, -5.29254181e-03,
        1.73163426e-03,  3.20439525e-02,  2.13081497e-04, -1.54123725e-02,
        5.08342534e-02, -4.52312343e-02, -1.67428404e-02, -3.47918682e-02,
       -4.16715406e-02, -2.34929174e-02,  2.40790378e-03, -2.15250961e-02,
        3.07013094e-03,  2.54970901e-02,  3.60133126e-02,  2.68478002e-02,
       -4.22386043e-02, -2.45388672e-02,  3.93797904e-02,  6.31313911e-03,
        2.03843638e-02, -2.22934633e-02, -7.87320361e-03, -1.47401327e-02,
        4.87235710e-02, -2.55933460e-02, -1.08921006e-02, -3.37022729e-02,
        4.69094813e-02,  1.95821337e-02,  4.13407665e-03,  2.72842553e-02,
        4.72949381e-04,  2.55070571e-02, -5.26176244e-02,  3.57674658e-02,
       -5.46482019e-03, -3.90752256e-02, -4.51455601e-02, -1.37631614e-02,
        5.50721325e-02,  3.80344279e-02, -4.58984412e-02,  4.83393949e-03,
       -2.92574633e-02, -4.76555573e-03,  9.17753279e-02, -9.70400721e-02,
        1.05631828e-01, -5.64411059e-02, -6.33300915e-02,  3.45335677e-02,
       -5.77132329e-02, -1.21777304e-01,  9.45342332e-03,  2.02731229e-02,
        2.63032019e-02,  3.96902720e-03, -3.88276428e-02, -1.57009140e-02,
       -3.47952247e-02, -3.07988320e-02,  3.24620530e-02, -4.84479591e-02,
        4.39476222e-03, -1.72206648e-02,  1.15609946e-04, -3.72782461e-02,
       -5.17302640e-02, -1.91914346e-02, -3.10722478e-02,  4.77237673e-03,
       -5.49006611e-02, -1.40048675e-02,  2.99301576e-02,  9.23176333e-02,
       -2.96304561e-02,  2.45515648e-02,  3.50713506e-02, -5.64086949e-03,
        1.57488920e-02,  2.08431389e-02,  5.11531830e-02,  7.25736795e-03,
        4.40724753e-03, -2.58072224e-02,  4.99892281e-03, -1.47747225e-03,
       -4.42322390e-03,  4.48388010e-02,  7.79227763e-02,  1.65748168e-02,
       -3.80822718e-02,  3.76828201e-02,  1.02415688e-01, -1.61058977e-02,
        7.32476562e-02, -1.11488095e-02,  3.81629355e-02,  2.02278662e-02,
       -1.23597020e-02,  2.38338504e-02, -2.99291853e-02, -7.08033796e-03,
        1.23009924e-02, -6.69545354e-03, -6.65793270e-02,  6.94696680e-02,
        1.02031687e-02, -2.23913062e-02, -1.79656297e-02, -3.10913660e-02,
       -3.04419808e-02, -2.43375860e-02,  2.62913741e-02, -1.44890947e-02,
       -3.44526842e-02,  3.69894737e-03,  2.34961957e-02, -2.20465418e-02,
       -6.40620366e-02, -3.29653509e-02, -1.13152396e-02,  4.46261205e-02,
        2.82178428e-02, -1.32326679e-02, -2.48316620e-02, -4.16193940e-02,
       -3.17104273e-02, -2.90311500e-03, -2.58374214e-02, -2.38407645e-02,
        4.09953259e-02, -3.72038893e-02,  3.80427018e-02,  2.60184593e-02,
        3.78452465e-02, -1.22930016e-02, -1.78747177e-02,  2.22685281e-02,
       -1.39293596e-02,  3.33373179e-03, -1.01043331e-02, -9.42679122e-02,
        2.93327998e-02, -2.11534109e-02, -8.28086492e-03,  9.39183310e-03,
        7.01195449e-02, -2.47648284e-02, -7.45414244e-03,  1.81595366e-02,
        2.10114084e-02,  5.30432425e-02, -1.83114391e-02,  2.45678425e-02,
        1.81325860e-02, -1.36736473e-02, -2.25673313e-03,  2.27259807e-02,
       -1.32561503e-02,  5.31734601e-02,  2.84622260e-03, -1.26052350e-02,
        5.37055396e-02, -2.62218006e-02,  6.28262013e-02, -3.38792838e-02,
        1.24346400e-02,  3.83224292e-03,  2.31522676e-02, -7.25013316e-02,
       -4.14393609e-03, -4.29395810e-02, -9.25686676e-03, -1.02920001e-02,
       -2.94399969e-02, -1.51161794e-02,  1.03488928e-02, -8.83047096e-03,
        7.79079879e-03,  6.15880676e-02, -2.56217923e-02,  2.67890431e-02,
       -3.48654948e-02, -3.35104279e-02,  4.58869450e-02,  2.87142433e-02,
       -1.73843279e-02,  9.46802422e-02, -2.42618304e-02,  2.83706822e-02,
        5.47284912e-03, -3.05396430e-02, -2.04882436e-02,  1.14951078e-02,
       -2.06157006e-02, -4.73047122e-02, -5.66246745e-04,  2.54014116e-02,
       -4.44826037e-02, -3.05528753e-02, -2.27482170e-02,  5.34625445e-03,
       -1.77380387e-02,  8.93085916e-03,  6.29965495e-03, -4.71266806e-02,
        9.71080363e-03, -1.98281463e-02, -1.95309147e-02,  2.61490308e-02,
        2.61223246e-03, -2.84732506e-02, -8.45033862e-03, -6.73168004e-02,
       -8.53152573e-02, -3.01742628e-02,  3.68127003e-02,  2.59252582e-02,
       -6.74630255e-02, -5.72894476e-02, -1.90711040e-02, -2.98832655e-02,
       -1.49018681e-02, -6.44187583e-03, -1.42151807e-02,  3.73985805e-02,
        1.12890743e-03,  2.28629522e-02, -4.47167754e-02,  2.30516475e-02,
        6.28957001e-04,  4.42759059e-02,  2.46650148e-02,  3.51332538e-02,
       -3.61626148e-02, -4.75540422e-02,  1.82497725e-02,  3.07629779e-02,
        1.00456458e-03, -1.84898656e-02, -2.19365447e-05,  7.50036165e-02,
        3.62004414e-02,  6.58765063e-02, -1.86647289e-02,  4.20117006e-02,
       -2.29520816e-03,  6.42548054e-02,  5.11614531e-02, -1.55825689e-02,
       -7.13906717e-04,  3.42612937e-02, -6.07561227e-03,  2.43100096e-02,
       -1.24312835e-02, -4.36682999e-02,  2.47560292e-02, -3.65800038e-02,
        2.03333907e-02, -3.50793153e-02,  1.50017273e-02,  7.63921514e-02,
        6.04431331e-02,  6.65943921e-02,  3.30557930e-03,  3.46694440e-02,
       -1.60531083e-03, -2.37293225e-02,  9.55966301e-03, -8.56768619e-03,
       -1.43413777e-02,  9.41571444e-02,  3.45746912e-02,  7.35701248e-02,
        2.54632197e-02, -3.96389663e-02,  2.52091214e-02,  7.53591806e-02,
       -3.82415466e-02, -3.73829231e-02, -5.41513376e-02,  2.40689144e-02,
       -3.08086872e-02, -6.20017666e-03, -7.64316414e-03, -3.59188356e-02,
        1.13590644e-03, -4.66337288e-03,  2.37280075e-02, -4.54728641e-02,
       -1.95232360e-03,  1.30089652e-02, -4.03874852e-02,  3.14237401e-02,
        3.25081423e-02,  2.98243649e-02, -7.06249848e-04, -8.04493353e-02,
       -1.45465778e-02, -1.17486315e-02, -3.25348228e-02,  3.16704623e-02,
       -4.22670208e-02,  6.71451390e-02, -1.01962581e-01, -3.84004414e-02,
       -1.90569460e-02,  5.59221022e-02,  7.67455017e-03,  5.18109836e-02,
        1.68128796e-02, -1.31116360e-02,  2.82035349e-03,  1.55517901e-03,
       -5.03696734e-04, -3.61106060e-02, -6.84429659e-03,  1.76924113e-02,
       -2.98450049e-02, -4.57745381e-02,  1.10833878e-02, -1.51629746e-02,
        3.66879231e-03,  8.08090419e-02, -1.80434845e-02, -1.02004060e-03,
       -4.84685937e-04,  3.22402902e-02, -1.65944472e-02,  1.84554583e-03,
        5.07567413e-02,  1.58889554e-02, -6.26498014e-02, -1.95618644e-02,
        4.34029624e-02, -5.68293072e-02,  1.05988346e-01, -4.80109155e-02,
        1.00578098e-02,  2.19856035e-02, -3.14385779e-02,  1.16583453e-02,
        3.97340804e-02, -1.13186799e-02,  5.83116822e-02,  2.77368701e-03,
        6.33229017e-02,  4.29549292e-02,  2.16282960e-02,  3.85455899e-02,
       -2.44158600e-02,  1.34006571e-02,  2.94844620e-03,  7.02530053e-03,
       -1.87546369e-02,  4.76556420e-02,  6.15999922e-02,  1.85416304e-02,
       -1.38640413e-02, -4.43654060e-02, -2.19828524e-02,  1.19858226e-02,
       -3.77185121e-02, -6.42945394e-02, -2.67555602e-02,  5.12968563e-02,
        2.78438460e-02, -6.28402382e-02, -3.17041092e-02,  2.21165456e-02,
       -1.41522791e-02, -6.07151585e-03,  7.16668069e-02,  1.14130257e-02,
        3.74975335e-03, -6.88136220e-02,  4.47597578e-02, -3.12533192e-02,
        1.41535681e-02, -3.08248587e-02, -7.57703034e-04, -5.60959196e-03,
        4.05325145e-02,  5.67561132e-04,  1.03435591e-02,  8.89484882e-02,
       -8.93703476e-03, -6.23021163e-02,  2.01754700e-02, -1.27847195e-02,
        1.61152259e-02, -1.23151019e-02,  2.49236263e-02,  2.02201903e-02,
       -2.01466382e-02,  4.14760113e-02, -2.72540469e-02, -3.96626405e-02,
       -2.26231758e-02,  1.40828069e-03,  1.52835315e-02, -6.26359060e-02,
        6.85891658e-02,  2.12807134e-02, -4.11787182e-02,  7.12970197e-02,
       -2.85411738e-02, -1.06836651e-02, -1.89546514e-02,  1.78564172e-02,
       -3.75272110e-02,  6.14918070e-04,  4.38691080e-02,  1.56059563e-02,
        3.15992371e-03,  5.58515964e-03, -5.97158028e-03,  2.85605397e-02,
       -9.22783278e-03,  9.27611068e-03,  2.80324835e-02,  6.93221316e-02,
       -3.44455279e-02, -2.25160290e-02,  2.57092062e-02, -4.39213730e-33,
       -3.64305452e-02, -2.59273336e-03,  9.11504775e-03,  3.95197384e-02,
        1.37440050e-02,  3.83440987e-03,  2.09220592e-03, -6.76697074e-03,
        1.25045814e-02, -1.33823799e-02, -1.84265955e-03,  1.20098041e-02,
        1.55763635e-02,  7.08836131e-04,  7.13026896e-02, -5.37558943e-02,
        2.44811513e-02, -4.40049656e-02, -1.36816707e-02, -1.33414501e-02,
       -2.93123070e-02, -1.21151423e-02,  6.02591559e-02,  1.02625899e-02,
        3.59789990e-02, -3.84313762e-02,  2.23757252e-02,  1.09116239e-02,
        6.93021864e-02,  1.61974728e-02, -3.05023920e-02,  4.06713262e-02,
       -3.92037369e-02, -3.48172300e-02,  4.40173224e-02,  2.78183036e-02,
       -5.45113534e-03, -2.34862641e-02,  9.80811380e-03,  2.96252910e-02,
        4.15044837e-02, -8.76813978e-02, -8.35824162e-02, -2.17031930e-02,
       -3.72131653e-02, -8.14556610e-03, -1.64230764e-02, -3.21030943e-03,
        7.74316723e-03, -4.88729924e-02, -3.05721373e-03, -2.07577702e-02,
        1.43916635e-02, -2.15989314e-02,  5.19237332e-02,  3.22398394e-02,
        2.97001842e-02,  6.64230585e-02,  3.49241979e-02,  6.32981583e-02,
        2.76506450e-02, -6.43676519e-02, -1.97427161e-02, -6.66220039e-02,
       -2.80176159e-02, -2.66223829e-02, -1.15307849e-02, -2.93885963e-03,
        2.88166497e-02, -3.48907150e-02,  1.28499428e-02,  2.38518268e-02,
       -2.04859450e-02,  3.24630253e-02,  2.07587127e-02,  3.60320583e-02,
        1.18891997e-02,  2.08263025e-02,  5.34499772e-02,  3.98998260e-02,
        1.93192333e-03,  4.08157334e-02,  1.73660871e-02,  1.62020531e-02,
       -3.99374329e-02, -5.42060249e-02, -9.92145296e-03, -2.20064092e-02,
        2.27758158e-02, -3.69535154e-03, -5.12674823e-02, -3.43792327e-02,
        2.70802993e-02,  6.55443268e-03, -8.59292001e-02, -6.78600073e-02,
       -6.93692919e-03,  1.56281237e-02, -6.14048215e-03,  1.97633859e-02,
       -2.56496519e-02, -8.55880324e-03, -6.69195922e-03, -1.37871420e-02,
       -1.60989650e-02, -6.38104556e-03,  4.70548905e-02, -3.73780611e-03,
       -2.61347685e-02,  9.47324268e-04,  5.62972622e-03, -4.70339209e-02,
       -2.40904242e-02, -1.03060208e-01,  3.95706110e-02,  1.86298043e-02,
        1.22608179e-02, -2.66108401e-02,  8.73115472e-03, -1.45035516e-02,
       -2.18206216e-02, -5.02304770e-02, -1.87203437e-02, -1.50403064e-02,
       -3.63761280e-03,  1.26317823e-02,  3.22695412e-02,  2.52542216e-02,
       -2.95263678e-02, -1.22713046e-02, -1.14217792e-02, -9.44962911e-03,
        1.85265691e-07, -3.20790373e-02,  2.90722027e-02,  1.50097441e-02,
        4.58585992e-02, -4.58980389e-02,  8.51313695e-02,  1.87605862e-02,
       -7.52922613e-03, -9.47736017e-03,  2.20605433e-02, -1.64591912e-02,
        1.37806190e-02, -5.93537092e-03,  1.98825486e-02, -1.72281619e-02,
       -5.15167788e-02,  7.51994550e-02, -2.18111742e-02,  1.31364832e-05,
       -4.08613496e-02, -2.18479224e-02,  7.75562301e-02,  6.59543723e-02,
        3.45364474e-02,  6.32863585e-03, -3.45287398e-02,  2.41718385e-02,
       -5.22142164e-02, -4.00036294e-03, -4.70077060e-02, -7.21946266e-03,
       -6.05984777e-02, -4.96256212e-03, -1.06797311e-02,  3.90087664e-02,
       -4.15890478e-03,  5.15687466e-02,  1.44929290e-02,  8.72998312e-03,
        5.83561845e-02, -4.20899875e-02, -3.73952417e-03, -4.08154465e-02,
       -3.81656736e-02,  2.13405606e-03,  3.52092111e-03, -6.06538774e-03,
       -2.75366884e-02, -1.17570246e-02, -2.33171927e-03,  2.78418865e-02,
       -2.67389081e-02,  2.94055492e-02, -3.15133817e-02, -4.89010056e-03,
       -3.41912685e-03,  4.42338362e-02,  1.56635735e-02,  1.01597551e-02,
       -8.11970159e-02, -8.74566285e-06,  4.35416773e-02, -3.40956845e-03,
        1.32463679e-01, -5.27368374e-02,  4.36557382e-02,  3.99109647e-02,
        6.80548322e-35,  2.35433616e-02, -4.56788763e-02, -3.64246927e-02,
        3.97049785e-02, -2.14084312e-02, -1.54701434e-03,  9.18157920e-02,
       -7.23868608e-03,  7.68457167e-03,  2.62084659e-02, -2.25905329e-03],
      dtype=float32)

In [44]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [45]:
svec

array([[ 1.03882691e-02,  2.78686285e-02, -1.18618710e-02,
         1.81327257e-02,  1.21984119e-03, -1.42995641e-02,
         1.96229368e-02,  2.07198318e-02, -2.23660935e-02,
         4.75626774e-02,  1.77976061e-02, -8.00333917e-03,
         2.53419522e-02,  5.26148640e-02,  8.44942406e-03,
        -1.63944215e-02,  1.02661494e-02, -2.74856109e-02,
         8.37067291e-02, -1.52885355e-02,  1.67682748e-02,
        -3.97142116e-03, -2.74348632e-02,  5.02091758e-02,
        -8.36521294e-03, -4.74075824e-02,  2.36915816e-02,
        -1.01186438e-02, -2.82840263e-02,  7.94265140e-03,
         4.21436168e-02, -4.19375999e-03, -1.91232357e-02,
        -3.12785394e-02,  1.24685050e-06, -1.04428437e-02,
        -2.19971444e-02, -8.66928026e-02, -1.88494497e-03,
        -2.54772231e-02, -9.72972624e-03,  7.93310255e-02,
        -3.55963632e-02, -3.05383728e-04, -1.12392241e-02,
        -3.88932489e-02,  5.49313761e-02,  1.35207981e-01,
        -8.19147453e-02,  1.18785072e-02, -9.01845656e-03,
         1.92544367e-02, -2.82723568e-02, -3.29266936e-02,
        -2.20106654e-02, -4.29835916e-02,  3.70104685e-02,
        -4.80649248e-02,  9.49257892e-03,  3.51585783e-02,
         4.88772467e-02, -3.28933634e-02, -1.24120517e-02,
        -1.64292939e-02,  3.93721089e-02,  2.69109719e-02,
         6.15458935e-02, -4.14122455e-03,  1.75675526e-02,
         1.53993415e-02,  9.60058253e-03, -5.69588272e-04,
        -4.83582541e-02,  4.25832123e-02,  1.10986000e-02,
        -4.66182418e-02, -2.10591801e-03, -5.81461154e-02,
         1.40413018e-02,  1.00883860e-02, -2.44589858e-02,
         1.42714167e-02, -2.10582279e-02,  7.38854259e-02,
        -2.23948881e-02,  1.38753317e-02, -1.33594673e-03,
         9.21318494e-03, -2.84222756e-02, -4.04207641e-03,
        -1.71393286e-02, -8.46521184e-03, -2.83984020e-02,
        -3.69299464e-02, -9.47201177e-02, -3.26580219e-02,
         2.60049943e-02,  1.31179057e-02,  1.51670882e-02,
        -2.12378916e-03,  1.48178022e-02,  1.37817143e-02,
         1.25304116e-02, -5.01475437e-03,  3.56063135e-02,
         5.93453869e-02, -5.03397435e-02, -9.55990888e-03,
        -7.23668933e-02,  9.45845246e-03,  1.54202739e-02,
        -7.03747384e-03, -3.10014673e-02, -8.86358973e-03,
        -2.98000704e-02, -8.84007737e-02, -2.25058924e-02,
        -3.25824358e-02,  4.78070490e-02,  2.14029476e-03,
         1.37757114e-03, -1.25066238e-02, -1.15712602e-02,
         2.34021824e-02,  3.43833375e-03,  2.69363020e-02,
        -6.23307340e-02, -5.29254181e-03,  1.73163426e-03,
         3.20439525e-02,  2.13081497e-04, -1.54123725e-02,
         5.08342534e-02, -4.52312343e-02, -1.67428404e-02,
        -3.47918682e-02, -4.16715406e-02, -2.34929174e-02,
         2.40790378e-03, -2.15250961e-02,  3.07013094e-03,
         2.54970901e-02,  3.60133126e-02,  2.68478002e-02,
        -4.22386043e-02, -2.45388672e-02,  3.93797904e-02,
         6.31313911e-03,  2.03843638e-02, -2.22934633e-02,
        -7.87320361e-03, -1.47401327e-02,  4.87235710e-02,
        -2.55933460e-02, -1.08921006e-02, -3.37022729e-02,
         4.69094813e-02,  1.95821337e-02,  4.13407665e-03,
         2.72842553e-02,  4.72949381e-04,  2.55070571e-02,
        -5.26176244e-02,  3.57674658e-02, -5.46482019e-03,
        -3.90752256e-02, -4.51455601e-02, -1.37631614e-02,
         5.50721325e-02,  3.80344279e-02, -4.58984412e-02,
         4.83393949e-03, -2.92574633e-02, -4.76555573e-03,
         9.17753279e-02, -9.70400721e-02,  1.05631828e-01,
        -5.64411059e-02, -6.33300915e-02,  3.45335677e-02,
        -5.77132329e-02, -1.21777304e-01,  9.45342332e-03,
         2.02731229e-02,  2.63032019e-02,  3.96902720e-03,
        -3.88276428e-02, -1.57009140e-02, -3.47952247e-02,
        -3.07988320e-02,  3.24620530e-02, -4.84479591e-02,
         4.39476222e-03, -1.72206648e-02,  1.15609946e-04,
        -3.72782461e-02, -5.17302640e-02, -1.91914346e-02,
        -3.10722478e-02,  4.77237673e-03, -5.49006611e-02,
        -1.40048675e-02,  2.99301576e-02,  9.23176333e-02,
        -2.96304561e-02,  2.45515648e-02,  3.50713506e-02,
        -5.64086949e-03,  1.57488920e-02,  2.08431389e-02,
         5.11531830e-02,  7.25736795e-03,  4.40724753e-03,
        -2.58072224e-02,  4.99892281e-03, -1.47747225e-03,
        -4.42322390e-03,  4.48388010e-02,  7.79227763e-02,
         1.65748168e-02, -3.80822718e-02,  3.76828201e-02,
         1.02415688e-01, -1.61058977e-02,  7.32476562e-02,
        -1.11488095e-02,  3.81629355e-02,  2.02278662e-02,
        -1.23597020e-02,  2.38338504e-02, -2.99291853e-02,
        -7.08033796e-03,  1.23009924e-02, -6.69545354e-03,
        -6.65793270e-02,  6.94696680e-02,  1.02031687e-02,
        -2.23913062e-02, -1.79656297e-02, -3.10913660e-02,
        -3.04419808e-02, -2.43375860e-02,  2.62913741e-02,
        -1.44890947e-02, -3.44526842e-02,  3.69894737e-03,
         2.34961957e-02, -2.20465418e-02, -6.40620366e-02,
        -3.29653509e-02, -1.13152396e-02,  4.46261205e-02,
         2.82178428e-02, -1.32326679e-02, -2.48316620e-02,
        -4.16193940e-02, -3.17104273e-02, -2.90311500e-03,
        -2.58374214e-02, -2.38407645e-02,  4.09953259e-02,
        -3.72038893e-02,  3.80427018e-02,  2.60184593e-02,
         3.78452465e-02, -1.22930016e-02, -1.78747177e-02,
         2.22685281e-02, -1.39293596e-02,  3.33373179e-03,
        -1.01043331e-02, -9.42679122e-02,  2.93327998e-02,
        -2.11534109e-02, -8.28086492e-03,  9.39183310e-03,
         7.01195449e-02, -2.47648284e-02, -7.45414244e-03,
         1.81595366e-02,  2.10114084e-02,  5.30432425e-02,
        -1.83114391e-02,  2.45678425e-02,  1.81325860e-02,
        -1.36736473e-02, -2.25673313e-03,  2.27259807e-02,
        -1.32561503e-02,  5.31734601e-02,  2.84622260e-03,
        -1.26052350e-02,  5.37055396e-02, -2.62218006e-02,
         6.28262013e-02, -3.38792838e-02,  1.24346400e-02,
         3.83224292e-03,  2.31522676e-02, -7.25013316e-02,
        -4.14393609e-03, -4.29395810e-02, -9.25686676e-03,
        -1.02920001e-02, -2.94399969e-02, -1.51161794e-02,
         1.03488928e-02, -8.83047096e-03,  7.79079879e-03,
         6.15880676e-02, -2.56217923e-02,  2.67890431e-02,
        -3.48654948e-02, -3.35104279e-02,  4.58869450e-02,
         2.87142433e-02, -1.73843279e-02,  9.46802422e-02,
        -2.42618304e-02,  2.83706822e-02,  5.47284912e-03,
        -3.05396430e-02, -2.04882436e-02,  1.14951078e-02,
        -2.06157006e-02, -4.73047122e-02, -5.66246745e-04,
         2.54014116e-02, -4.44826037e-02, -3.05528753e-02,
        -2.27482170e-02,  5.34625445e-03, -1.77380387e-02,
         8.93085916e-03,  6.29965495e-03, -4.71266806e-02,
         9.71080363e-03, -1.98281463e-02, -1.95309147e-02,
         2.61490308e-02,  2.61223246e-03, -2.84732506e-02,
        -8.45033862e-03, -6.73168004e-02, -8.53152573e-02,
        -3.01742628e-02,  3.68127003e-02,  2.59252582e-02,
        -6.74630255e-02, -5.72894476e-02, -1.90711040e-02,
        -2.98832655e-02, -1.49018681e-02, -6.44187583e-03,
        -1.42151807e-02,  3.73985805e-02,  1.12890743e-03,
         2.28629522e-02, -4.47167754e-02,  2.30516475e-02,
         6.28957001e-04,  4.42759059e-02,  2.46650148e-02,
         3.51332538e-02, -3.61626148e-02, -4.75540422e-02,
         1.82497725e-02,  3.07629779e-02,  1.00456458e-03,
        -1.84898656e-02, -2.19365447e-05,  7.50036165e-02,
         3.62004414e-02,  6.58765063e-02, -1.86647289e-02,
         4.20117006e-02, -2.29520816e-03,  6.42548054e-02,
         5.11614531e-02, -1.55825689e-02, -7.13906717e-04,
         3.42612937e-02, -6.07561227e-03,  2.43100096e-02,
        -1.24312835e-02, -4.36682999e-02,  2.47560292e-02,
        -3.65800038e-02,  2.03333907e-02, -3.50793153e-02,
         1.50017273e-02,  7.63921514e-02,  6.04431331e-02,
         6.65943921e-02,  3.30557930e-03,  3.46694440e-02,
        -1.60531083e-03, -2.37293225e-02,  9.55966301e-03,
        -8.56768619e-03, -1.43413777e-02,  9.41571444e-02,
         3.45746912e-02,  7.35701248e-02,  2.54632197e-02,
        -3.96389663e-02,  2.52091214e-02,  7.53591806e-02,
        -3.82415466e-02, -3.73829231e-02, -5.41513376e-02,
         2.40689144e-02, -3.08086872e-02, -6.20017666e-03,
        -7.64316414e-03, -3.59188356e-02,  1.13590644e-03,
        -4.66337288e-03,  2.37280075e-02, -4.54728641e-02,
        -1.95232360e-03,  1.30089652e-02, -4.03874852e-02,
         3.14237401e-02,  3.25081423e-02,  2.98243649e-02,
        -7.06249848e-04, -8.04493353e-02, -1.45465778e-02,
        -1.17486315e-02, -3.25348228e-02,  3.16704623e-02,
        -4.22670208e-02,  6.71451390e-02, -1.01962581e-01,
        -3.84004414e-02, -1.90569460e-02,  5.59221022e-02,
         7.67455017e-03,  5.18109836e-02,  1.68128796e-02,
        -1.31116360e-02,  2.82035349e-03,  1.55517901e-03,
        -5.03696734e-04, -3.61106060e-02, -6.84429659e-03,
         1.76924113e-02, -2.98450049e-02, -4.57745381e-02,
         1.10833878e-02, -1.51629746e-02,  3.66879231e-03,
         8.08090419e-02, -1.80434845e-02, -1.02004060e-03,
        -4.84685937e-04,  3.22402902e-02, -1.65944472e-02,
         1.84554583e-03,  5.07567413e-02,  1.58889554e-02,
        -6.26498014e-02, -1.95618644e-02,  4.34029624e-02,
        -5.68293072e-02,  1.05988346e-01, -4.80109155e-02,
         1.00578098e-02,  2.19856035e-02, -3.14385779e-02,
         1.16583453e-02,  3.97340804e-02, -1.13186799e-02,
         5.83116822e-02,  2.77368701e-03,  6.33229017e-02,
         4.29549292e-02,  2.16282960e-02,  3.85455899e-02,
        -2.44158600e-02,  1.34006571e-02,  2.94844620e-03,
         7.02530053e-03, -1.87546369e-02,  4.76556420e-02,
         6.15999922e-02,  1.85416304e-02, -1.38640413e-02,
        -4.43654060e-02, -2.19828524e-02,  1.19858226e-02,
        -3.77185121e-02, -6.42945394e-02, -2.67555602e-02,
         5.12968563e-02,  2.78438460e-02, -6.28402382e-02,
        -3.17041092e-02,  2.21165456e-02, -1.41522791e-02,
        -6.07151585e-03,  7.16668069e-02,  1.14130257e-02,
         3.74975335e-03, -6.88136220e-02,  4.47597578e-02,
        -3.12533192e-02,  1.41535681e-02, -3.08248587e-02,
        -7.57703034e-04, -5.60959196e-03,  4.05325145e-02,
         5.67561132e-04,  1.03435591e-02,  8.89484882e-02,
        -8.93703476e-03, -6.23021163e-02,  2.01754700e-02,
        -1.27847195e-02,  1.61152259e-02, -1.23151019e-02,
         2.49236263e-02,  2.02201903e-02, -2.01466382e-02,
         4.14760113e-02, -2.72540469e-02, -3.96626405e-02,
        -2.26231758e-02,  1.40828069e-03,  1.52835315e-02,
        -6.26359060e-02,  6.85891658e-02,  2.12807134e-02,
        -4.11787182e-02,  7.12970197e-02, -2.85411738e-02,
        -1.06836651e-02, -1.89546514e-02,  1.78564172e-02,
        -3.75272110e-02,  6.14918070e-04,  4.38691080e-02,
         1.56059563e-02,  3.15992371e-03,  5.58515964e-03,
        -5.97158028e-03,  2.85605397e-02, -9.22783278e-03,
         9.27611068e-03,  2.80324835e-02,  6.93221316e-02,
        -3.44455279e-02, -2.25160290e-02,  2.57092062e-02,
        -4.39213730e-33, -3.64305452e-02, -2.59273336e-03,
         9.11504775e-03,  3.95197384e-02,  1.37440050e-02,
         3.83440987e-03,  2.09220592e-03, -6.76697074e-03,
         1.25045814e-02, -1.33823799e-02, -1.84265955e-03,
         1.20098041e-02,  1.55763635e-02,  7.08836131e-04,
         7.13026896e-02, -5.37558943e-02,  2.44811513e-02,
        -4.40049656e-02, -1.36816707e-02, -1.33414501e-02,
        -2.93123070e-02, -1.21151423e-02,  6.02591559e-02,
         1.02625899e-02,  3.59789990e-02, -3.84313762e-02,
         2.23757252e-02,  1.09116239e-02,  6.93021864e-02,
         1.61974728e-02, -3.05023920e-02,  4.06713262e-02,
        -3.92037369e-02, -3.48172300e-02,  4.40173224e-02,
         2.78183036e-02, -5.45113534e-03, -2.34862641e-02,
         9.80811380e-03,  2.96252910e-02,  4.15044837e-02,
        -8.76813978e-02, -8.35824162e-02, -2.17031930e-02,
        -3.72131653e-02, -8.14556610e-03, -1.64230764e-02,
        -3.21030943e-03,  7.74316723e-03, -4.88729924e-02,
        -3.05721373e-03, -2.07577702e-02,  1.43916635e-02,
        -2.15989314e-02,  5.19237332e-02,  3.22398394e-02,
         2.97001842e-02,  6.64230585e-02,  3.49241979e-02,
         6.32981583e-02,  2.76506450e-02, -6.43676519e-02,
        -1.97427161e-02, -6.66220039e-02, -2.80176159e-02,
        -2.66223829e-02, -1.15307849e-02, -2.93885963e-03,
         2.88166497e-02, -3.48907150e-02,  1.28499428e-02,
         2.38518268e-02, -2.04859450e-02,  3.24630253e-02,
         2.07587127e-02,  3.60320583e-02,  1.18891997e-02,
         2.08263025e-02,  5.34499772e-02,  3.98998260e-02,
         1.93192333e-03,  4.08157334e-02,  1.73660871e-02,
         1.62020531e-02, -3.99374329e-02, -5.42060249e-02,
        -9.92145296e-03, -2.20064092e-02,  2.27758158e-02,
        -3.69535154e-03, -5.12674823e-02, -3.43792327e-02,
         2.70802993e-02,  6.55443268e-03, -8.59292001e-02,
        -6.78600073e-02, -6.93692919e-03,  1.56281237e-02,
        -6.14048215e-03,  1.97633859e-02, -2.56496519e-02,
        -8.55880324e-03, -6.69195922e-03, -1.37871420e-02,
        -1.60989650e-02, -6.38104556e-03,  4.70548905e-02,
        -3.73780611e-03, -2.61347685e-02,  9.47324268e-04,
         5.62972622e-03, -4.70339209e-02, -2.40904242e-02,
        -1.03060208e-01,  3.95706110e-02,  1.86298043e-02,
         1.22608179e-02, -2.66108401e-02,  8.73115472e-03,
        -1.45035516e-02, -2.18206216e-02, -5.02304770e-02,
        -1.87203437e-02, -1.50403064e-02, -3.63761280e-03,
         1.26317823e-02,  3.22695412e-02,  2.52542216e-02,
        -2.95263678e-02, -1.22713046e-02, -1.14217792e-02,
        -9.44962911e-03,  1.85265691e-07, -3.20790373e-02,
         2.90722027e-02,  1.50097441e-02,  4.58585992e-02,
        -4.58980389e-02,  8.51313695e-02,  1.87605862e-02,
        -7.52922613e-03, -9.47736017e-03,  2.20605433e-02,
        -1.64591912e-02,  1.37806190e-02, -5.93537092e-03,
         1.98825486e-02, -1.72281619e-02, -5.15167788e-02,
         7.51994550e-02, -2.18111742e-02,  1.31364832e-05,
        -4.08613496e-02, -2.18479224e-02,  7.75562301e-02,
         6.59543723e-02,  3.45364474e-02,  6.32863585e-03,
        -3.45287398e-02,  2.41718385e-02, -5.22142164e-02,
        -4.00036294e-03, -4.70077060e-02, -7.21946266e-03,
        -6.05984777e-02, -4.96256212e-03, -1.06797311e-02,
         3.90087664e-02, -4.15890478e-03,  5.15687466e-02,
         1.44929290e-02,  8.72998312e-03,  5.83561845e-02,
        -4.20899875e-02, -3.73952417e-03, -4.08154465e-02,
        -3.81656736e-02,  2.13405606e-03,  3.52092111e-03,
        -6.06538774e-03, -2.75366884e-02, -1.17570246e-02,
        -2.33171927e-03,  2.78418865e-02, -2.67389081e-02,
         2.94055492e-02, -3.15133817e-02, -4.89010056e-03,
        -3.41912685e-03,  4.42338362e-02,  1.56635735e-02,
         1.01597551e-02, -8.11970159e-02, -8.74566285e-06,
         4.35416773e-02, -3.40956845e-03,  1.32463679e-01,
        -5.27368374e-02,  4.36557382e-02,  3.99109647e-02,
         6.80548322e-35,  2.35433616e-02, -4.56788763e-02,
        -3.64246927e-02,  3.97049785e-02, -2.14084312e-02,
        -1.54701434e-03,  9.18157920e-02, -7.23868608e-03,
         7.68457167e-03,  2.62084659e-02, -2.25905329e-03]], dtype=float32)

In [46]:
distances, I = index.search(svec, k=2)

In [47]:
I

array([[3, 2]])

In [48]:
#faiss.normalize_L2(svec)

In [49]:
I.tolist()

[[3, 2]]

In [50]:
row_indices = I.tolist()[0]
row_indices

[3, 2]

In [51]:
df.loc[row_indices]

                                                text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [52]:
search_query

'I want to buy a polo t-shirt'

In [53]:
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel

In [54]:
!pip install streamlit
import os
import streamlit as st
import pickle
import time
import langchain
from langchain import OpenAI
from langchain.chains import RetrievalQAWithSourcesChain
from langchain.chains.qa_with_sources.loading import load_qa_with_sources_chain
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import UnstructuredURLLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS

Collecting streamlit
  Downloading streamlit-1.45.0-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging<25,>=20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (11.2.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.29.4)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (4.13.2)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.11/dist-packages (from streamlit) (3.1.44)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.11/dist-packages (from streamlit) (6.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (1.37.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2025.4.26)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.24.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.45.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 41.9 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 60.4 MB/s eta 0:00:00
Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 7.3 MB/s eta 0:00:00
Installing collected packages: watchdog, pydeck, streamlit
Successfully installed pydeck-0.9.1 streamlit-1.45.0 watchdog-6.0.0

In [71]:
#load openAI api key
os.environ['OPENAI_API_KEY'] = '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'

In [72]:
# Initialise LLM with required params
llm = OpenAI(temperature=0.9, max_tokens=500)

(1) Load data

In [73]:
loaders = UnstructuredURLLoader(urls=[
    "https://www.moneycontrol.com/news/business/markets/wall-street-rises-as-tesla-soars-on-ai-optimism-11351111.html",
    "https://www.moneycontrol.com/news/business/tata-motors-launches-punch-icng-price-starts-at-rs-7-1-lakh-11098751.html"
])
data = loaders.load()
len(data)

2

In [74]:
#(2) Split data to create chunks
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

# As data is of type documents we can directly use split_documents over split_text in order to get the chunks.
docs = text_splitter.split_documents(data)

In [75]:
len(docs)

17

In [76]:
docs[0]

Document(metadata={'source': 'https://www.moneycontrol.com/news/business/markets/wall-street-rises-as-tesla-soars-on-ai-optimism-11351111.html'}, page_content='English\n\nHindi\n\nGujarati\n\nSpecials\n\nHello, Login\n\nHello, Login\n\nLog-inor Sign-Up\n\nMy Account\n\nMy Profile\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nMy Profile\n\nMy PRO\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nLogout\n\nLoans up to ₹50 LAKHS\n\nFixed Deposits\n\nCredit CardsLifetime Free\n\nCredit Score\n\nChat with Us\n\nDownload App\n\nFollow us on:\n\nNetwork 18\n\nGo Ad-Free\n\nMy Alerts\n\n>->MC_ENG_DESKTOP/MC_ENG_NEWS/MC_ENG_MARKETS_AS/MC_ENG_ROS_NWS_MKTS_AS_ATF_728\n\nMoneycontrol\n\nGo PRO NowPRO\n\nMoneycontrol PRO\n\nAdvertisement\n\nRemove Ad\n\nBusiness\n\nMarkets\n\nStocks\n\nEconomy\n\nCompanies\n\nTrends\n\nIPO\n\nOpinion\n\nEV Special\n\nOffer Subscription Products\n\nprofile\n\nAmbareesh Baliga\n\nprofile\n\nCK Narayan\n\nprofile\n\nT Gnanasekar\n\nprofile\n\nPower Your Trade\n\nprofile\n\nCurrencies with Mecklai Financial\n\nprofile\n\nStock Reports\n\nHomeNewsBusinessMarketsWall Street rises as Tesla soars on AI optimism\n\nTrending Topics')

In [77]:
!pip install tiktoken
#Create embeddings for these chunks and save them to FAISS index
# Create the embeddings of the chunks using openAIEmbeddings
embeddings = OpenAIEmbeddings()

Requirement already satisfied: tiktoken in /usr/local/lib/python3.11/dist-packages (0.9.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.11/dist-packages (from tiktoken) (2024.11.6)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.11/dist-packages (from tiktoken) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->tiktoken) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->tiktoken) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->tiktoken) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.26.0->tiktoken) (2025.4.26)

In [78]:
pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (3.4.1)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.51.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.15.2)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (0.30.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.4.26)

In [79]:
from langchain.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
vectorindex = FAISS.from_documents(docs, embeddings)

In [80]:

# Pass the documents and embeddings inorder to create FAISS vector index
vectorindex_openai = FAISS.from_documents(docs, embeddings)

In [81]:
# Storing vector index create in local
file_path="vector_index.pkl"
with open(file_path, "wb") as f:
    pickle.dump(vectorindex_openai, f)

In [82]:

if os.path.exists(file_path):
    with open(file_path, "rb") as f:
        vectorIndex = pickle.load(f)

In [83]:
#4) Retrieve similar embeddings for a given question and call LLM to retrieve final answer

chain = RetrievalQAWithSourcesChain.from_llm(llm=llm, retriever=vectorIndex.as_retriever())
chain

RetrievalQAWithSourcesChain(verbose=False, combine_documents_chain=MapReduceDocumentsChain(verbose=False, llm_chain=LLMChain(verbose=False, prompt=PromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, template='Use the following portion of a long document to see if any of the text is relevant to answer the question. \nReturn any relevant text verbatim.\n{context}\nQuestion: {question}\nRelevant text, if any:'), llm=OpenAI(client=<openai.resources.completions.Completions object at 0x7bc5bb228690>, async_client=<openai.resources.completions.AsyncCompletions object at 0x7bc5bb23f650>, temperature=0.9, max_tokens=500, model_kwargs={}, openai_api_key='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', openai_proxy='', logit_bias={}), output_parser=StrOutputParser(), llm_kwargs={}), reduce_documents_chain=ReduceDocumentsChain(verbose=False, combine_documents_chain=StuffDocumentsChain(verbose=False, llm_chain=LLMChain(verbose=False, prompt=PromptTemplate(input_variables=['question', 'summaries'], input_types={}, partial_variables={}, template='Given the following extracted parts of a long document and a question, create a final answer with references ("SOURCES"). \nIf you don\'t know the answer, just say that you don\'t know. Don\'t try to make up an answer.\nALWAYS return a "SOURCES" part in your answer.\n\nQUESTION: Which state/country\'s law governs the interpretation of the contract?\n=========\nContent: This Agreement is governed by English law and the parties submit to the exclusive jurisdiction of the English courts in  relation to any dispute (contractual or non-contractual) concerning this Agreement save that either party may apply to any court for an  injunction or other relief to protect its Intellectual Property Rights.\nSource: 28-pl\nContent: No Waiver. Failure or delay in exercising any right or remedy under this Agreement shall not constitute a waiver of such (or any other)  right or remedy.\n\n11.7 Severability. The invalidity, illegality or unenforceability of any term (or part of a term) of this Agreement shall not affect the continuation  in force of the remainder of the term (if any) and this Agreement.\n\n11.8 No Agency. Except as expressly stated otherwise, nothing in this Agreement shall create an agency, partnership or joint venture of any  kind between the parties.\n\n11.9 No Third-Party Beneficiaries.\nSource: 30-pl\nContent: (b) if Google believes, in good faith, that the Distributor has violated or caused Google to violate any Anti-Bribery Laws (as  defined in Clause 8.5) or that such a violation is reasonably likely to occur,\nSource: 4-pl\n=========\nFINAL ANSWER: This Agreement is governed by English law.\nSOURCES: 28-pl\n\nQUESTION: What did the president say about Michael Jackson?\n=========\nContent: Madam Speaker, Madam Vice President, our First Lady and Second Gentleman. Members of Congress and the Cabinet. Justices of the Supreme Court. My fellow Americans.  \n\nLast year COVID-19 kept us apart. This year we are finally together again. \n\nTonight, we meet as Democrats Republicans and Independents. But most importantly as Americans. \n\nWith a duty to one another to the American people to the Constitution. \n\nAnd with an unwavering resolve that freedom will always triumph over tyranny. \n\nSix days ago, Russia’s Vladimir Putin sought to shake the foundations of the free world thinking he could make it bend to his menacing ways. But he badly miscalculated. \n\nHe thought he could roll into Ukraine and the world would roll over. Instead he met a wall of strength he never imagined. \n\nHe met the Ukrainian people. \n\nFrom President Zelenskyy to every Ukrainian, their fearlessness, their courage, their determination, inspires the world. \n\nGroups of citizens blocking tanks with their bodies. Everyone from students to retirees teachers turned soldiers defending their homeland.\nSource: 0-pl\nContent: And we won’t stop. \n\nWe have lost so much to COVID-19. Time with one another. And worst of all, so much loss of life. \n\nLet’s use this moment to reset. Let’s stop looking at COVID-19 as a partisan dividing line and see it for what it is: A God-awful disease.  \n\nLet’s stop seeing each other as enemies, and start seeing each other for who we really are: Fellow Americans.  \n\nWe can’t change how divided we’ve been. But we can change how we move forward—on COVID-19 and other issues we must face together. \n\nI recently visited the New York City Police Department days after the funerals of Officer Wilbert Mora and his partner, Officer Jason Rivera. \n\nThey were responding to a 9-1-1 call when a man shot and killed them with a stolen gun. \n\nOfficer Mora was 27 years old. \n\nOfficer Rivera was 22. \n\nBoth Dominican Americans who’d grown up on the same streets they later chose to patrol as police officers. \n\nI spoke with their families and told them that we are forever in debt for their sacrifice, and we will carry on their mission to restore the trust and safety every community deserves.\nSource: 24-pl\nContent: And a proud Ukrainian people, who have known 30 years  of independence, have repeatedly shown that they will not tolerate anyone who tries to take their country backwards.  \n\nTo all Americans, I will be honest with you, as I’ve always promised. A Russian dictator, invading a foreign country, has costs around the world. \n\nAnd I’m taking robust action to make sure the pain of our sanctions  is targeted at Russia’s economy. And I will use every tool at our disposal to protect American businesses and consumers. \n\nTonight, I can announce that the United States has worked with 30 other countries to release 60 Million barrels of oil from reserves around the world.  \n\nAmerica will lead that effort, releasing 30 Million barrels from our own Strategic Petroleum Reserve. And we stand ready to do more if necessary, unified with our allies.  \n\nThese steps will help blunt gas prices here at home. And I know the news about what’s happening can seem alarming. \n\nBut I want you to know that we are going to be okay.\nSource: 5-pl\nContent: More support for patients and families. \n\nTo get there, I call on Congress to fund ARPA-H, the Advanced Research Projects Agency for Health. \n\nIt’s based on DARPA—the Defense Department project that led to the Internet, GPS, and so much more.  \n\nARPA-H will have a singular purpose—to drive breakthroughs in cancer, Alzheimer’s, diabetes, and more. \n\nA unity agenda for the nation. \n\nWe can do this. \n\nMy fellow Americans—tonight , we have gathered in a sacred space—the citadel of our democracy. \n\nIn this Capitol, generation after generation, Americans have debated great questions amid great strife, and have done great things. \n\nWe have fought for freedom, expanded liberty, defeated totalitarianism and terror. \n\nAnd built the strongest, freest, and most prosperous nation the world has ever known. \n\nNow is the hour. \n\nOur moment of responsibility. \n\nOur test of resolve and conscience, of history itself. \n\nIt is in this moment that our character is formed. Our purpose is found. Our future is forged. \n\nWell I know this nation.\nSource: 34-pl\n=========\nFINAL ANSWER: The president did not mention Michael Jackson.\nSOURCES:\n\nQUESTION: {question}\n=========\n{summaries}\n=========\nFINAL ANSWER:'), llm=OpenAI(client=<openai.resources.completions.Completions object at 0x7bc5bb228690>, async_client=<openai.resources.completions.AsyncCompletions object at 0x7bc5bb23f650>, temperature=0.9, max_tokens=500, model_kwargs={}, openai_api_key='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', openai_proxy='', logit_bias={}), output_parser=StrOutputParser(), llm_kwargs={}), document_prompt=PromptTemplate(input_variables=['page_content', 'source'], input_types={}, partial_variables={}, template='Content: {page_content}\nSource: {source}'), document_variable_name='summaries')), document_variable_name='context'), retriever=VectorStoreRetriever(tags=['FAISS', 'HuggingFaceEmbeddings'], vectorstore=<langchain_community.vectorstores.faiss.FAISS object at 0x7bc5ba464b90>, search_kwargs={}))

In [85]:
query = "what is the price of Tiago iCNG?"

langchain.debug=True

In [86]:
chain({"question": query}, return_only_outputs=True)

[chain/start] [chain:RetrievalQAWithSourcesChain] Entering Chain run with input:
{
  "question": "what is the price of Tiago iCNG?"
}
[chain/start] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain] Entering Chain run with input:
[inputs]
[chain/start] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain > chain:LLMChain] Entering Chain run with input:
{
  "input_list": [
    {
      "context": "The company also said it has also introduced the twin-cylinder technology on its Tiago and Tigor models.\n\nThe Tiago iCNG is priced between Rs 6.55 lakh and Rs 8.1 lakh, while the Tigor iCNG comes at a price range of Rs 7.8 lakh to Rs 8.95 lakh.\n\nTata Motors Passenger Vehicles Ltd Head-Marketing, Vinay Pant said these introductions put together will make the company's CNG line up \"appealing, holistic, and stronger than ever\".\n\nPTI\n\nfirst published: Aug 4, 2023 02:17 pm\n\nDiscover the latest Business News, Budget 2025 News, Sensex, and Nifty updates. Obtain Personal Finance insights, tax queries, and expert opinions on Moneycontrol or download the Moneycontrol App to stay updated!\n\nAdvertisement\n\nRemove Ad\n\nAdvertisement\n\nRemove Ad\n\nAdvertisement\n\nRemove Ad\n\nAdvertisement\n\nRemove Ad\n\nAdvertisement\n\nRemove Ad\n\nAdvertisement\n\nRemove Ad\n\nAdvisory Alert:\n\nmoneycontrol\n\nFollow Us On:\n\nFacebook\n\ntwitter\n\ninstagram\n\nlinkedin\n\ntelegram\n\nyoutube",
      "question": "what is the price of Tiago iCNG?"
    },
    {
      "context": "profile\n\nPower Your Trade\n\nprofile\n\nCurrencies with Mecklai Financial\n\nprofile\n\nStock Reports\n\nHomeNewsBusinessTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nTrending Topics\n\nGST Collections in AprilSensex LiveAther Energy IPO GMPIndia US Trade DealGautam Singhania\n\nTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nThe Punch iCNG is equipped with the company's proprietary twin-cylinder technology with enhanced safety features like a micro-switch to keep the car switched off at the time of refuelling and thermal incident protection that cuts off CNG supply to the engine and releases gas into the atmosphere, Tata Motors said in a statement.\n\nPTI\n\nAugust 04, 2023 / 14:17 IST\n\nTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nWatchlist\n\nPortfolio\n\nMessage\n\nSet Alert\n\nlive\n\nbselive\n\nnselive\n\nVolume\n\nTodays L/H\n\nMore",
      "question": "what is the price of Tiago iCNG?"
    },
    {
      "context": "Tata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nWatchlist\n\nPortfolio\n\nMessage\n\nSet Alert\n\nlive\n\nbselive\n\nnselive\n\nVolume\n\nTodays L/H\n\nMore\n\nTata Motors on Friday launched the CNG variant of its micro SUV Punch priced between Rs 7.1 lakh and Rs 9.68 lakh (ex-showroom, Delhi).\n\nThe Punch iCNG is equipped with the company's proprietary twin-cylinder technology with enhanced safety features like a micro-switch to keep the car switched off at the time of refuelling and thermal incident protection that cuts off CNG supply to the engine and releases gas into the atmosphere, Tata Motors said in a statement.\n\nStory continues below Advertisement\n\nRemove Ad\n\nIt is also equipped with other features such as voice assisted electric sunroof, automatic projector headlamps, LED DRLs, 16-inch diamond cut alloy wheels, 7-inch infotainment system by Harman that supports Android Auto and Apple Carplay connectivity, rain sensing wipers and height adjustable driver seat.",
      "question": "what is the price of Tiago iCNG?"
    },
    {
      "context": "English\n\nHindi\n\nGujarati\n\nSpecials\n\nHello, Login\n\nHello, Login\n\nLog-inor Sign-Up\n\nMy Account\n\nMy Profile\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nMy Profile\n\nMy PRO\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nLogout\n\nLoans up to ₹50 LAKHS\n\nFixed Deposits\n\nCredit CardsLifetime Free\n\nCredit Score\n\nChat with Us\n\nDownload App\n\nFollow us on:\n\nNetwork 18\n\nGo Ad-Free\n\nMy Alerts\n\n>->MC_ENG_DESKTOP/MC_ENG_NEWS/MC_ENG_BUSINESS_AS/MC_ENG_ROS_NWS_BUS_AS_ATF_728\n\nMoneycontrol\n\nGo PRO NowPRO\n\nMoneycontrol PRO\n\nAdvertisement\n\nRemove Ad\n\nBusiness\n\nMarkets\n\nStocks\n\nEconomy\n\nCompanies\n\nTrends\n\nIPO\n\nOpinion\n\nEV Special\n\nOffer Subscription Products\n\nprofile\n\nAmbareesh Baliga\n\nprofile\n\nCK Narayan\n\nprofile\n\nT Gnanasekar\n\nprofile\n\nPower Your Trade\n\nprofile\n\nCurrencies with Mecklai Financial\n\nprofile\n\nStock Reports\n\nHomeNewsBusinessTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nTrending Topics",
      "question": "what is the price of Tiago iCNG?"
    }
  ]
}
[llm/start] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain > chain:LLMChain > llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "Use the following portion of a long document to see if any of the text is relevant to answer the question. \nReturn any relevant text verbatim.\nThe company also said it has also introduced the twin-cylinder technology on its Tiago and Tigor models.\n\nThe Tiago iCNG is priced between Rs 6.55 lakh and Rs 8.1 lakh, while the Tigor iCNG comes at a price range of Rs 7.8 lakh to Rs 8.95 lakh.\n\nTata Motors Passenger Vehicles Ltd Head-Marketing, Vinay Pant said these introductions put together will make the company's CNG line up \"appealing, holistic, and stronger than ever\".\n\nPTI\n\nfirst published: Aug 4, 2023 02:17 pm\n\nDiscover the latest Business News, Budget 2025 News, Sensex, and Nifty updates. Obtain Personal Finance insights, tax queries, and expert opinions on Moneycontrol or download the Moneycontrol App to stay updated!\n\nAdvertisement\n\nRemove Ad\n\nAdvertisement\n\nRemove Ad\n\nAdvertisement\n\nRemove Ad\n\nAdvertisement\n\nRemove Ad\n\nAdvertisement\n\nRemove Ad\n\nAdvertisement\n\nRemove Ad\n\nAdvisory Alert:\n\nmoneycontrol\n\nFollow Us On:\n\nFacebook\n\ntwitter\n\ninstagram\n\nlinkedin\n\ntelegram\n\nyoutube\nQuestion: what is the price of Tiago iCNG?\nRelevant text, if any:"
  ]
}
[llm/start] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain > chain:LLMChain > llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "Use the following portion of a long document to see if any of the text is relevant to answer the question. \nReturn any relevant text verbatim.\nprofile\n\nPower Your Trade\n\nprofile\n\nCurrencies with Mecklai Financial\n\nprofile\n\nStock Reports\n\nHomeNewsBusinessTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nTrending Topics\n\nGST Collections in AprilSensex LiveAther Energy IPO GMPIndia US Trade DealGautam Singhania\n\nTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nThe Punch iCNG is equipped with the company's proprietary twin-cylinder technology with enhanced safety features like a micro-switch to keep the car switched off at the time of refuelling and thermal incident protection that cuts off CNG supply to the engine and releases gas into the atmosphere, Tata Motors said in a statement.\n\nPTI\n\nAugust 04, 2023 / 14:17 IST\n\nTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nWatchlist\n\nPortfolio\n\nMessage\n\nSet Alert\n\nlive\n\nbselive\n\nnselive\n\nVolume\n\nTodays L/H\n\nMore\nQuestion: what is the price of Tiago iCNG?\nRelevant text, if any:"
  ]
}
[llm/start] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain > chain:LLMChain > llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "Use the following portion of a long document to see if any of the text is relevant to answer the question. \nReturn any relevant text verbatim.\nTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nWatchlist\n\nPortfolio\n\nMessage\n\nSet Alert\n\nlive\n\nbselive\n\nnselive\n\nVolume\n\nTodays L/H\n\nMore\n\nTata Motors on Friday launched the CNG variant of its micro SUV Punch priced between Rs 7.1 lakh and Rs 9.68 lakh (ex-showroom, Delhi).\n\nThe Punch iCNG is equipped with the company's proprietary twin-cylinder technology with enhanced safety features like a micro-switch to keep the car switched off at the time of refuelling and thermal incident protection that cuts off CNG supply to the engine and releases gas into the atmosphere, Tata Motors said in a statement.\n\nStory continues below Advertisement\n\nRemove Ad\n\nIt is also equipped with other features such as voice assisted electric sunroof, automatic projector headlamps, LED DRLs, 16-inch diamond cut alloy wheels, 7-inch infotainment system by Harman that supports Android Auto and Apple Carplay connectivity, rain sensing wipers and height adjustable driver seat.\nQuestion: what is the price of Tiago iCNG?\nRelevant text, if any:"
  ]
}
[llm/start] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain > chain:LLMChain > llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "Use the following portion of a long document to see if any of the text is relevant to answer the question. \nReturn any relevant text verbatim.\nEnglish\n\nHindi\n\nGujarati\n\nSpecials\n\nHello, Login\n\nHello, Login\n\nLog-inor Sign-Up\n\nMy Account\n\nMy Profile\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nMy Profile\n\nMy PRO\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nLogout\n\nLoans up to ₹50 LAKHS\n\nFixed Deposits\n\nCredit CardsLifetime Free\n\nCredit Score\n\nChat with Us\n\nDownload App\n\nFollow us on:\n\nNetwork 18\n\nGo Ad-Free\n\nMy Alerts\n\n>->MC_ENG_DESKTOP/MC_ENG_NEWS/MC_ENG_BUSINESS_AS/MC_ENG_ROS_NWS_BUS_AS_ATF_728\n\nMoneycontrol\n\nGo PRO NowPRO\n\nMoneycontrol PRO\n\nAdvertisement\n\nRemove Ad\n\nBusiness\n\nMarkets\n\nStocks\n\nEconomy\n\nCompanies\n\nTrends\n\nIPO\n\nOpinion\n\nEV Special\n\nOffer Subscription Products\n\nprofile\n\nAmbareesh Baliga\n\nprofile\n\nCK Narayan\n\nprofile\n\nT Gnanasekar\n\nprofile\n\nPower Your Trade\n\nprofile\n\nCurrencies with Mecklai Financial\n\nprofile\n\nStock Reports\n\nHomeNewsBusinessTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nTrending Topics\nQuestion: what is the price of Tiago iCNG?\nRelevant text, if any:"
  ]
}
[llm/error] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain > chain:LLMChain > llm:OpenAI] [2.10s] LLM run errored with error:
"RateLimitError(\"Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}\")Traceback (most recent call last):\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/llms.py\", line 790, in _generate_helper\n    self._generate(\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_community/llms/openai.py\", line 463, in _generate\n    response = completion_with_retry(\n               ^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_community/llms/openai.py\", line 121, in completion_with_retry\n    return llm.client.create(**kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_utils/_utils.py\", line 287, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/resources/completions.py\", line 541, in create\n    return self._post(\n           ^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_base_client.py\", line 1239, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_base_client.py\", line 1034, in request\n    raise self._make_status_error_from_response(err.response) from None\n\n\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}"
[llm/error] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain > chain:LLMChain > llm:OpenAI] [2.11s] LLM run errored with error:
"RateLimitError(\"Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}\")Traceback (most recent call last):\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/llms.py\", line 790, in _generate_helper\n    self._generate(\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_community/llms/openai.py\", line 463, in _generate\n    response = completion_with_retry(\n               ^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_community/llms/openai.py\", line 121, in completion_with_retry\n    return llm.client.create(**kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_utils/_utils.py\", line 287, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/resources/completions.py\", line 541, in create\n    return self._post(\n           ^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_base_client.py\", line 1239, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_base_client.py\", line 1034, in request\n    raise self._make_status_error_from_response(err.response) from None\n\n\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}"
[llm/error] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain > chain:LLMChain > llm:OpenAI] [2.11s] LLM run errored with error:
"RateLimitError(\"Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}\")Traceback (most recent call last):\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/llms.py\", line 790, in _generate_helper\n    self._generate(\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_community/llms/openai.py\", line 463, in _generate\n    response = completion_with_retry(\n               ^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_community/llms/openai.py\", line 121, in completion_with_retry\n    return llm.client.create(**kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_utils/_utils.py\", line 287, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/resources/completions.py\", line 541, in create\n    return self._post(\n           ^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_base_client.py\", line 1239, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_base_client.py\", line 1034, in request\n    raise self._make_status_error_from_response(err.response) from None\n\n\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}"
[llm/error] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain > chain:LLMChain > llm:OpenAI] [2.11s] LLM run errored with error:
"RateLimitError(\"Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}\")Traceback (most recent call last):\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_core/language_models/llms.py\", line 790, in _generate_helper\n    self._generate(\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_community/llms/openai.py\", line 463, in _generate\n    response = completion_with_retry(\n               ^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/langchain_community/llms/openai.py\", line 121, in completion_with_retry\n    return llm.client.create(**kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_utils/_utils.py\", line 287, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/resources/completions.py\", line 541, in create\n    return self._post(\n           ^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_base_client.py\", line 1239, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/usr/local/lib/python3.11/dist-packages/openai/_base_client.py\", line 1034, in request\n    raise self._make_status_error_from_response(err.response) from None\n\n\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}"
[chain/error] [chain:RetrievalQAWithSourcesChain > chain:MapReduceDocumentsChain > chain:LLMChain] [2.11s] Chain run errored with error:

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}